name: unifi
version: 5.13.29
summary: Unifi Network controller software.
description: |
  Unifi Network controller software.
base: core18
confinement: strict
grade: stable
architectures:
 - build-on: arm64
parts:
  mongodb:
    plugin: nil
    source: https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-arm64/mongodb-org-mongos_3.6.18_arm64.deb

  unifi:
    plugin: nil
    stage-packages: [openjdk-8-jre, jsvc]
    source: https://dl.ui.com/unifi/5.13.29/unifi_sysvinit_all.deb

# apps:
#   start-unifi:
#     command: 
#     daemon: simple
